# Small code to split the original data into training and testing sets

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

np.random.seed(1234)

In [2]:
data = pd.read_csv('../train_data/AllOriginal.csv')
print("Length of data before dropping NaN: ", len(data))
data = data.dropna()
print("Length of data after dropping NaN: ", len(data))

Length of data before dropping NaN:  2425
Length of data after dropping NaN:  2424

In [3]:
data.head()

,Unnamed: 0,APOGEE_ID_1,source_id,LOGG,TEFF,ALPHA_M,M_H,C_FE,N_FE,G,...,age_68L,ageErr,logAge,logAgeErr,distKpc,distKpc_68u,distKpc_68l,distErrKpc,logDistKpc,logDistKpcErr
0,0,2M19252021+3647118,2050240782362231552,2.822838,4636.0260,0.022572,0.275174,0.020502,0.419455,12.049109,...,4.8417,1.35930,0.779149,0.096771,1.232919,1.251669,1.214507,0.018581,0.090935,0.006545
1,3,2M19250718+3654252,2050245627085389184,2.775030,4803.0825,0.004583,-0.008960,-0.141116,0.373124,11.912818,...,3.2810,0.95270,0.618707,0.099430,1.268516,1.286735,1.249425,0.018655,0.103296,0.006390
2,4,2M19252149+3654097,2050244733732234112,2.930188,4818.7980,-0.011045,0.106488,-0.209060,0.382780,10.622860,...,3.2734,0.94180,0.612455,0.098699,0.638877,0.649120,0.630231,0.009445,-0.194583,0.006413
3,7,2M19225688+3702125,2051009615863922176,2.608446,4678.4697,0.016243,-0.052954,-0.030310,0.230492,11.939016,...,5.9566,2.08205,0.889711,0.115106,1.229117,1.248787,1.207286,0.020750,0.089593,0.007339
4,9,2M19264298+3704199,2051751030300733440,2.749369,4778.7530,-0.006691,0.157371,-0.142914,0.400376,11.502472,...,2.0184,0.56035,0.392169,0.095899,1.159074,1.177103,1.141563,0.017770,0.064111,0.006657

In [4]:
data_train, data_test = train_test_split(data, test_size = 0.20, random_state = 42)

In [5]:
data_train.head()

,Unnamed: 0,APOGEE_ID_1,source_id,LOGG,TEFF,ALPHA_M,M_H,C_FE,N_FE,G,...,age_68L,ageErr,logAge,logAgeErr,distKpc,distKpc_68u,distKpc_68l,distErrKpc,logDistKpc,logDistKpcErr
2201,3007,2M19245919+4904405,2129924451604211840,2.703328,5051.3477,-0.024964,0.015620,-0.193154,0.362376,11.237647,...,0.5932,0.04525,-0.196065,0.030832,1.367700,1.378745,1.356813,0.010966,0.135991,0.003482
1845,2524,2M19384701+4654120,2128522161963536256,2.560836,4902.2150,0.009692,-0.237355,-0.022189,0.141674,12.622266,...,3.5892,0.99950,0.651598,0.096137,1.769168,1.793244,1.743813,0.024716,0.247769,0.006070
1853,2532,2M19492511+4658097,2080358123831833984,2.582711,4677.4550,0.000431,-0.031245,-0.148458,0.306092,12.632368,...,4.9057,1.38305,0.812171,0.097098,1.890041,1.916411,1.866637,0.024887,0.276471,0.005714
2345,3191,2M19480970+5010211,2087267901574848128,2.864075,4702.1416,0.012963,0.129694,0.026458,0.284040,13.277733,...,7.4989,2.18560,0.972522,0.099728,1.767200,1.792612,1.742208,0.025202,0.247286,0.006193
2005,2749,2M18460389+4755134,2119641196087016192,2.818272,5101.4260,0.043301,-0.148103,-0.088330,0.262368,12.230013,...,1.5115,0.40255,0.269933,0.092721,1.221320,1.237325,1.204730,0.016297,0.086829,0.005797

In [6]:
len(data_train)

1939

In [7]:
len(data_test)

485

In [8]:
data_train.to_csv('../train_data/TrainingOriginal.csv')
data_test.to_csv('../test_data/TestOriginal.csv')